### ISSUE TITLE
cant find location of server folder

### ISSUE THREAD

**Issue by FearlessNite345** [RouHim/beammp-container-image#28]
i am unable to locate where it makes the server folder?

**Comment by RouHim** [comment]
Are you using docker run or the docker compose example? And are you familiar with docker at all ? :D

**Comment by FearlessNite345** [comment]
using the docker with CasaOS and im pretty new to running servers and using Docker

**Comment by RouHim** [comment]
Oh ok, so let's have a look together. How looks your command line you execute?

**Comment by RouHim** [comment]
Closed due to inactivity, if you need still help just let me know.

**Comment by BJET67** [comment]
I'm also having an issue trying to find the location of the server folder (docker/Linux noob) I'm trying to add custom maps and mods
