### ISSUE TITLE
Question: Execute commands

### ISSUE THREAD

**Issue by Grifed-source** [RouHim/beammp-container-image#33]
Hello,

I'm working with this BeamMP Docker repository and am trying to figure out how to execute commands in the console. Is there any documentation or guidance available on this?

Thanks for your assistance.

**Comment by RouHim** [comment]
Hello @Grifed-source,
can you give me an example command or a reference to a documentation what you mean. 
Greetings

**Comment by RouHim** [comment]
Ah I see, there is an interactive way of communicating with the server. Currently this is not supported. I have to check this.

**Comment by RouHim** [comment]
Ok, this is possible by running the container with the "-it" option.
E.g.:
`docker run -it -e AUTH_KEY='test' rouhim/beammp-server `

**Comment by Grifed-source** [comment]
This command making a new beammp server, no? I tried to do `docker attach <container name>` but I can't execute commands in the console

**Comment by RouHim** [comment]
This is a docker related question and not specific to my container image thus I need more information about your setup in order to help you.
