### ISSUE TITLE
[FEATURE] Can't use console after docker compose && docker compose up -d

### ISSUE THREAD

**Issue by redbirdjs** [RouHim/beammp-container-image#34]
I can attach to the container, but I can't run any console commands

**Comment by RouHim** [comment]
Hello @redbirdjs,
in order to help you, I really need some more information:
- Host OS
- Docker version
- Docker-compose version
- Excerpt from your docker compose file
- Command you are executing

Thanks

**Comment by redbirdjs** [comment]
Hi here are the information you needed:

- Host OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-1040-oracle aarch64)
- Docker version: Docker version 24.0.5, build ced0996
- Docker-compose version: Docker Compose version v2.20.2
- docker-compose file:

version: "3"

services:
  beammp-server:
    image: rouhim/beammp-server
    build:
      context: .
    environment:
      # Game server parameter
      - PRIVATE
      - DEBUG
      - CARS
      - MAX_PLAYERS
      - MAP
      - NAME
      - DESC
      - PORT
      - AUTH_KEY
      - ADDITIONAL_SERVER_CONFIG_TOML
    volumes:
      # Just move all the client mods you want to add into this folder
      - ./client-mods:/beammp/Resources/Client
      # All server mods belong here
      - ./server-mods:/beammp/Resources/Server
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${PORT}:${PORT}/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

- I executed this command: "docker attach beammp-docker-beammp-server-1"

**Comment by RouHim** [comment]
Thanks, I'll have a look and report back.

**Comment by RouHim** [comment]
@redbirdjs Should be fixed. Thanks for reporting!
