### ISSUE TITLE
3.1.2 New Version Available Warning

### ISSUE THREAD

**Issue by KemalBT** [RouHim/beammp-container-image#43]
I am getting error at server logs like `[03/12/23 17:39:03.369] Heartbeat [WARN] NEW VERSION IS OUT! Please update to the new version (v3.1.2) of the BeamMP-Server! Download it here: https://beammp.com/! For a guide on how to update, visit: https://wiki.beammp.com/en/home/server-maintenance#updating-the-server`

There is another problem that started very recently;
And i figured out the docker image closes after work for a while. But its might be related custom mods or there is a newest version things idk. @RouHim

**Comment by RouHim** [comment]
@KemalBT Should be fixed, please pull the latest image and try again.

**Comment by KemalBT** [comment]
Thank you @RouHim it's solved...

**Comment by RouHim** [comment]
If one of the other issues you are facing persists, please open a new issue.
