### ISSUE TITLE
[BUG] Fix broken arm64 build

### ISSUE THREAD

**Issue by RouHim** [RouHim/beammp-container-image#46]
Since the new build system introduced by beammp server, the arm64 build is broken.

Related issue in beammp repo is: https://github.com/BeamMP/BeamMP-Server/issues/205

**Comment by KemalBT** [comment]
Hi @RouHim today I saw that there was an update on beamng and I deleted my current image and entered your docker hub and what did I see, there is no arm64 version and there is no previous versions :) I wish there was a previous version.

**Comment by RouHim** [comment]
Sadly this would not help you in any way, because the old beammp Sever is incompatible with the latest version of beamng.
You could upvote my issue in the beammp repository.

**Comment by lionkor** [comment]
The old BeamMP Server is fully compatible with the current version of the game/launcher :)

**Comment by KemalBT** [comment]
@RouHim Hi, there is some update at base repo related open Arm64 task from @lionkor , it was closed when i checked. If i can help you for new build just ping me thanks.

**Comment by yalcinpak** [comment]
Thank you @RouHim @lionkor your works are invaluable helpful for us.

**Comment by RouHim** [comment]
Sadly I'm still facing issues when compiling for arm64. I don't have much time atm to troubleshoot this.

**Comment by KemalBT** [comment]
Hi @RouHim, i think issue not resolved completely i'll share a problem with screenshot, first section related docker pull command, other section related my server arch.
<img width="1082" alt="Screenshot 2023-12-30 at 22 15 33" src="https://github.com/RouHim/beammp-container-image/assets/3890805/02c7b815-1c72-4c79-895f-2a5f054aa6d2">

**Comment by RouHim** [comment]
Sorry github auto closed the issue

**Comment by RouHim** [comment]
I pushed an updated arm64 image, please try to use it.

**Comment by KemalBT** [comment]
Its working, thanks for your patience and support :) @RouHim

**Comment by RouHim** [comment]
Awesome, thanks for the coffee ☕.
