### ISSUE TITLE
[qusetion] Update underlying BeamMP server

### ISSUE THREAD

**Issue by RealFX-Code** [RouHim/beammp-container-image#47]
How do I update the BeamMP server version? Since the logs from my container keeps complaining about an outdated server.

Thanks in advance!
![image](https://github.com/RouHim/beammp-container-image/assets/25106569/84fa074c-a51c-4b86-9f8e-36b8490110ed)

**Comment by RouHim** [comment]
Hey @RealFX-Code, just do the following:
* `docker pull rouhim/beammp-server`
* Stop your docker container
* Start your docker container

**Comment by RealFX-Code** [comment]
Yea that worked, Thanks!
