### ISSUE TITLE
Extra S on value BEAMMP_MAX_PLAYERS

### ISSUE THREAD

**Issue by ashmaker000** [RouHim/beammp-container-image#55]
Hey,
Im pulling this latest container and have notices one of the values have a extra S, if I remove it it comes back when I redeploy
Value:
**BEAMMP_MAX_PLAYERSS**

![image](https://github.com/RouHim/beammp-container-image/assets/8276382/9cb0cc4f-3e84-482f-b1df-e917e87b92b8)

Green is the after remove the S and red is once I've re-deployed when it gets automatically added.

**Comment by RouHim** [comment]
Uff my bad, should be fixed.

**Comment by RouHim** [comment]
Thanks for reporting <3
