### ISSUE TITLE
The BeamMP server binary doesn't download correctly.

### ISSUE THREAD

**Issue by weekOldRoadkill** [RouHim/beammp-container-image#56]
The code on line 17-23 of `Containerfile` downloads a text file that says `Not Found` instead of the BeamMP server binary.

**Comment by weekOldRoadkill** [comment]
The problem seems to be that on my machine `uname -m` returns `aarch64` instead of `arm64`, so its trying to install `https://github.com/BeamMP/BeamMP-Server/releases/download/v3.2.2/BeamMP-Server.ubuntu.22.04.aarch64` instead of `https://github.com/BeamMP/BeamMP-Server/releases/download/v3.2.2/BeamMP-Server.ubuntu.22.04.arm64`.

**Comment by weekOldRoadkill** [comment]
Let me mention that the docker hub image was working for me until like last week.

**Comment by weekOldRoadkill** [comment]
Also on another note you should probably be using `apt-get` instead of `apt` in `Containerfile` due to the unstable CLI warning.

**Comment by RouHim** [comment]
Thanks for your contribution <3

**Comment by RouHim** [comment]
You can follow the pipeline here: https://github.com/RouHim/beammp-container-image/actions/runs/7593635085

I added an additional check, to ensure the downloaded binary is present (https://github.com/RouHim/beammp-container-image/commit/27e37b766078f11fd3639b911c4783bcc69769e4)
